spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/admin
      primary:
        uri: mongodb://root:123456@localhost:27017/primary
      secondary:
        uri: mongodb://root:123456@localhost:27017/secondary



