spring:
  data:
    mongodb:
      primary:
        host: localhost:27017
        username: root
        password: 123456
        database: admin
      secondary:
        host: localhost:27017
        username: root
        password: 123456
        database: config



